apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: APP_ENV
        - name: WELCOME
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: WELCOME_MESSAGE
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: password

